steps:
  push-latest:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO%%-service}
      tags: latest
      purge: true
    secrets: [docker_username, docker_password]
when:
  branch: master
  event: push
